version: '3.8'

services:
  bank-service:
    build:
      context: ./bank-service
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    links:
      - postgres
    networks:
      - backend

  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: pgUser
      POSTGRES_PASSWORD: pgPass!!1234
      POSTGRES_DB: bankdb
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U pgUser -d bankdb" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres:
    driver: local