// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/wallet": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wallet"
                ],
                "summary": "create",
                "parameters": [
                    {
                        "description": "WalletCreateRequest",
                        "name": "WalletCreateRequest",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/bankService_internal_commands_commandRequest.WalletCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/bankService_internal_commands_commandResponse.ErrorReponse"
                        }
                    }
                }
            }
        },
        "/wallets": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wallet"
                ],
                "summary": "get all",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/bankService_internal_commands_commandResponse.WalletResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/bankService_internal_commands_commandResponse.ErrorReponse"
                        }
                    }
                }
            }
        },
        "/wallets/{id}": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Wallet"
                ],
                "summary": "get",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Id",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/bankService_internal_commands_commandResponse.WalletResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/bankService_internal_commands_commandResponse.ErrorReponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "bankService_internal_commands_commandRequest.WalletCreateRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                },
                "operation": {
                    "type": "string"
                }
            }
        },
        "bankService_internal_commands_commandResponse.ErrorReponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "bankService_internal_commands_commandResponse.WalletItem": {
            "type": "object",
            "properties": {
                "ballance": {
                    "type": "integer"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "bankService_internal_commands_commandResponse.WalletResponse": {
            "type": "object",
            "properties": {
                "result": {
                    "$ref": "#/definitions/bankService_internal_commands_commandResponse.WalletItem"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Api Bank Service",
	Description:      "bank rest application",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
